name: csec
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=2.16=mkl
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cudatoolkit=11.3.1=hb98b00a_13
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libdeflate=1.14=h166bdaf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.4.0=h82bc61c_5
  - libuv=1.48.0=hd590300_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h4ab18f5_6
  - mkl=2020.2=256
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - numpy=1.21.6=py37h976b520_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.3.1=hb9d3cd8_3
  - pillow=9.2.0=py37h850a105_2
  - pip=22.3.1=py37h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=4_cp37m
  - pytorch=1.10.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.10.0=py37_cu113
  - torchvision=0.11.0=py37_cu113
  - typing_extensions=4.7.1=pyha770c72_0
  - wheel=0.38.4=py37h06a4308_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==24.2.0
      - backcall==0.2.0
      - cachetools==5.5.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cycler==0.11.0
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.34.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.3
      - hydra-core==1.3.2
      - idna==3.8
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipdb==0.13.13
      - ipython==7.34.0
      - jedi==0.19.1
      - kiwisolver==1.4.5
      - kornia==0.6.12
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - multidict==6.0.5
      - networkx==2.6.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - packaging==24.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.0.0
      - prompt-toolkit==3.0.47
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydeprecate==0.3.2
      - pygments==2.17.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.7.6
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-image==0.19.3
      - scipy==1.7.3
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - setuptools==59.5.0
      - six==1.16.0
      - smmap==5.0.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tifffile==2021.11.2
      - tomli==2.0.1
      - torchmetrics==0.11.4
      - tqdm==4.66.5
      - traitlets==5.9.0
      - urllib3==2.0.7
      - wandb==0.17.8
      - wcwidth==0.2.13
      - werkzeug==2.2.3
      - yarl==1.9.4
      - zipp==3.15.0
prefix: /home/user/anaconda3/envs/env_name
